In [1]:
# 1. exercises
import numpy as np
print(np.__version__)


1.21.5


In [2]:
# 2. exercises
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 3. exercises
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
# 4 .exercises
arr = np.arange(10)
arr[arr %2 == 1]

array([1, 3, 5, 7, 9])

In [6]:
# 5. exercises
arr[arr %2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
# 6. exercises
arr = np.arange(10)
out = np.where(arr % 3 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2,  3, -1,  5,  6, -1,  8,  9])

In [8]:
# 7. exercises
arr = np.arange(10)
arr.reshape(5, -1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
# 8. exercises
a = np.arange(10).reshape(2,-1)
b = np.repeat(2, 10).reshape(2,-1)

print(a)
print(b)
# Answers
# Method 1: https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html
np.concatenate([a, b], axis=0)

# Method 2: https://numpy.org/doc/stable/reference/generated/numpy.vstack.html
np.vstack([a, b])

# Method 3: https://numpy.org/doc/stable/reference/generated/numpy.r_.html
np.r_[a, b]

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[2 2 2 2 2]
 [2 2 2 2 2]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [10]:
# 9 exercises
# np.arange: 
# np.reshape: 
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1: https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html
np.concatenate([a, b], axis=1)

# Method 2: https://numpy.org/doc/stable/reference/generated/numpy.hstack.html
np.hstack([a, b])

# Method 3: https://numpy.org/doc/stable/reference/generated/numpy.c_.html
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [11]:
# 10. exercises
a = np.array([1,2,3])
# np.r_: https://numpy.org/doc/stable/reference/generated/numpy.r_.html
# np.repeat: https://numpy.org/doc/stable/reference/generated/numpy.repeat.html
# np.tile: https://numpy.org/doc/stable/reference/generated/numpy.tile.html
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [12]:
# 11. exercises
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# np.intersect1d: https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html
np.intersect1d(a,b)

array([2, 4])

In [13]:
# 12. exercises
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,1,9])
# np.setdiff1d: https://numpy.org/doc/stable/reference/generated/numpy.setdiff1d.html
np.setdiff1d(a,b)

array([2, 3, 4])

In [14]:
# 13. exercises
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# np.where: https://numpy.org/doc/stable/reference/generated/numpy.where.html
np.where(a == b)

(array([1, 3, 5, 7]),)

In [15]:
# 14. exercises
a = np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
# np.where: https://numpy.org/doc/stable/reference/generated/numpy.where.html
# np.logical_and: https://numpy.org/doc/stable/reference/generated/numpy.logical_and.html
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

In [16]:
# 15. exercises: Suche das größere Skalar aus zwei Arrays, an der Stellt i
# 15. exercises part 1
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
maxx(1,5)

5

In [17]:
# 15. exercises part 2
# np.vectorize: 
pair_max = np.vectorize(maxx, otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [18]:
# 16. exercises
arr = np.arange(9).reshape(3,3)
print(arr)
# Solution
print(arr[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [19]:
# 17. exercises
arr = np.arange(9).reshape(3,3)
print(arr)
# Solution
print(arr[[1,0,2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [20]:
# 18. exercises
arr = np.arange(9).reshape(3,3)
print(arr)
# Solution
print(arr[::-1,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [21]:
# 19. exercises
arr = np.arange(9).reshape(3,3)
print(arr)
# Solution
print(arr[:, ::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [22]:
# 20. exercises
arr = np.arange(9).reshape(3,3)

# Solution Method 1:
# np.random:
# np.randint:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

# Solution Method 2:
# np.uniform:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[7.25419439 7.25640755 6.29418903]
 [7.79562659 8.92737622 8.90364694]
 [6.65903793 9.07913664 7.70801758]
 [9.32182035 5.88271416 5.21988508]
 [7.53867424 8.1109245  9.73279776]]
[[7.05786789 9.14839635 9.79436451]
 [6.3974629  8.84056265 7.4044341 ]
 [7.54977711 8.83056203 6.25418261]
 [7.51011766 7.26798988 9.0997175 ]
 [6.91363347 8.51077505 8.84542045]]


In [23]:
# 21. exercises
rand_arr = np.random.random((5,3))

# Create the random array
rand_arr = np.random.random([5,3])

# Limit to 3 decimal places
# np.set_printoptions: 
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.954, 0.758, 0.56 ],
       [0.792, 0.477, 0.029],
       [0.908, 0.974, 0.313],
       [0.711, 0.737, 0.587]])

In [24]:
# 22 exercises
# Reset printoptions to default
# np.set_printoptions
np.set_printoptions(suppress=False)

# np.random.seed: 
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)
np.set_printoptions(suppress=True, precision=6)  # precision is optional
print(rand_arr)

[[5.434e-04 2.784e-04 4.245e-04]
 [8.448e-04 4.719e-06 1.216e-04]
 [6.707e-04 8.259e-04 1.367e-04]]
[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [25]:
# 23 exercises
# np.set_printoptions: 
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [26]:
# 24 exercises
# np.set_printoptions: 
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)
# Solution
# np.nan
np.set_printoptions(threshold=0)
print(a)

[ 0  1  2 ... 12 13 14]
[ 0  1  2 ... 12 13 14]


In [27]:
# 25 exercises
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris)
# Print the first 3 rows
iris[:3]

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 ...
 [b'6.5' b'3.0' b'5.2' b'2.0' b'Iris-virginica']
 [b'6.2' b'3.4' b'5.4' b'2.3' b'Iris-virginica']
 [b'5.9' b'3.0' b'5.1' b'1.8' b'Iris-virginica']]


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)