In [1]:
# 1. exercises
import numpy as np
print(np.__version__)


1.22.3


In [2]:
# 2. exercises
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 3. exercises
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
# 4 .exercises
arr = np.arange(10)
arr[arr %2 == 1]

array([1, 3, 5, 7, 9])

In [7]:
# 5. exercises
arr[arr %2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
# 6. exercises


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])