In [1]:
# Exercise 3 (JULIA)
A_max = rand(2, 4)

2×4 Array{Float64,2}:
 0.371518  0.532302  0.173886  0.267906
 0.303509  0.463328  0.939539  0.334072

In [2]:
max = findmax(A_max)

(0.9395392098442144, CartesianIndex(2, 3))

In [3]:
# Exercise 4 (JULIA)
# 4.1
A = rand(Int.(1:10), 2, 2)
B = rand(Int.(1:10), 2, 2)

2×2 Array{Int64,2}:
 7  9
 2  7

In [4]:
show(A)
show(B)

[8 7; 9 1][7 9; 2 7]

In [5]:
# Addinition.
# 4.1
M_add = A + B

2×2 Array{Int64,2}:
 15  16
 11   8

In [6]:
# Subtraction
# 4.1
M_sub = A - B

2×2 Array{Int64,2}:
 1  -2
 7  -6

In [7]:
# Multiplication 1
# 4.2
M_mul_1 = A * B

2×2 Array{Int64,2}:
 70  121
 65   88

In [8]:
# Multiplication 2
# 4.2
M_mul_2 = A. * B

LoadError: syntax: extra token "B" after end of expression

In [9]:
# Division 1.
# 4.3
M_diff_1 = A / B

2×2 Array{Float64,2}:
 1.35484  -0.741935
 1.96774  -2.3871

In [10]:
# Division 2.
#4.3
M_diff_2 = A \ B

2×2 Array{Float64,2}:
 0.127273  0.727273
 0.854545  0.454545

In [13]:
#
# 4.4
M_int = rand(Int.(1:10), 3, 3)
M_of_ones = ones(Int, 3,3)

3×3 Array{Int64,2}:
 1  1  1
 1  1  1
 1  1  1

In [14]:
show(M_int)

[10 2 3; 2 1 3; 4 6 1]

In [15]:
show(M_of_ones)

[1 1 1; 1 1 1; 1 1 1]

In [16]:
# 4.4
M_add_1 = M_int + 1 * M_of_ones

3×3 Array{Int64,2}:
 11  3  4
  3  2  4
  5  7  2

In [17]:
M_diff_1 = M_int - 1 * M_of_ones

3×3 Array{Int64,2}:
 9  1  2
 1  0  2
 3  5  0